name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://nuget.pkg.github.com/rcangus/index.json
      env: 
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Install dependencies
      run: dotnet restore Logging.Services.CustomLogger/Service.Logging.CustomLogger.sln --configfile Logging.Services.CustomLogger/Service.Logging.CustomLogger/nuget.config
    - name: Build
      run: dotnet build Logging.Services.CustomLogger/Service.Logging.CustomLogger.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
