name: .NET Core

on:
  push:
    branches: [ main ]
    paths: 
     - 'ConsoleAppToTestPackages/**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://nuget.pkg.github.com/rcangus/index.json
      env: 
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
    - name: Install dependencies
      run: dotnet restore ConsoleAppToTestPackages/ConsoleAppToTestPackages.sln 
    - name: Build
      run: dotnet build ConsoleAppToTestPackages/ConsoleAppToTestPackages.sln --configuration Release --no-restore
    
